name: "Buildozer-Kivy-Apk-Creator"
description: "Use Buildozer To Make Apk From Kivy Framework (Python)"
author: "wildspider57389928"
branding:
  icon: "archive"
  color: "blue"
inputs:
  project-dir:
    description: "Building Directory"
    required: true

runs:name: Build_APK

on:
  workflow_call:
    inputs:
      project-dir:
        required: true
        type: string
        default: .
      command:
        required: true
        type: string
        default: buildozer android debug
        
jobs:
  build-android:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fix Git extraheader permission issue
        run: git config --global --unset-all "http.https://github.com/.extraheader" || true

      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          workdir: ${{ inputs.project-dir }}
          buildozer_version: stable
          command: ${{ inputs.command }}

      - name: Compute tag
        id: vars
        run: echo "tag=v0.0.${{ github.run_number }}" >> $GITHUB_OUTPUT

      - name: Upload file to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.vars.outputs.tag }}
          files: ${{ steps.buildozer.outputs.filename }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
