name: "Buildozer-Kivy-Apk-Creator"
description: "Use Buildozer To Make Apk From Kivy Framework (Python)"
author: "wildspider57389928"
branding:
  icon: "archive"
  color: "blue"
inputs:
  project-dir:
    description: "Building Directory"
    required: true

runs:
  using: "composite"
  steps:
    - name: Call build workflow
      uses: ./.github/workflows/build.yml
      with:
        project-dir: ${{ inputs.project-dir }
